//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcQualification
    {
        public AcQualification()
        {
            this.Papers = new HashSet<Paper>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public int AcqLevelId { get; set; }
        public int CVId { get; set; }
    
        public virtual AcQualificationLevel AcQualificationLevel { get; set; }
        public virtual ICollection<Paper> Papers { get; set; }
        public virtual CV CV { get; set; }
    }
}
