//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.CoverLetters = new HashSet<CoverLetter>();
            this.SoftSkills = new HashSet<SoftSkill>();
        }
    
        public int Id { get; set; }
        public int JobTitleId { get; set; }
        public int RequiredAcqLevelId { get; set; }
        public int JobTypeId { get; set; }
        public int EmployerId { get; set; }
        public bool Activated { get; set; }
        public string JobDescription { get; set; }
    
        public virtual AcQualificationLevel AcQualificationLevel { get; set; }
        public virtual ICollection<CoverLetter> CoverLetters { get; set; }
        public virtual Employer Employer { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual ICollection<SoftSkill> SoftSkills { get; set; }
    }
}
