//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingExprience
    {
        public int Id { get; set; }
        public System.DateTime Start { get; set; }
        public Nullable<System.DateTime> Finish { get; set; }
        public string JobTitle { get; set; }
        public string Company { get; set; }
        public string RoleDescription { get; set; }
        public int CId { get; set; }
    
        public virtual CV CV { get; set; }
    }
}
