//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV
    {
        public CV()
        {
            this.VdQualifications = new HashSet<VdQualification>();
            this.WorkingExpriences = new HashSet<WorkingExprience>();
            this.AcQualifications = new HashSet<AcQualification>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string StudentId { get; set; }
    
        public virtual Graduate Graduate { get; set; }
        public virtual ICollection<VdQualification> VdQualifications { get; set; }
        public virtual ICollection<WorkingExprience> WorkingExpriences { get; set; }
        public virtual ICollection<AcQualification> AcQualifications { get; set; }
    }
}
