//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paper
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int GId { get; set; }
        public int AcQId { get; set; }
    
        public virtual AcQualification AcQualification { get; set; }
        public virtual Grade Grade { get; set; }
    }
}
