//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSoftskillLevel
    {
        public int SoftSkillId { get; set; }
        public int SoftSkillLevelId { get; set; }
        public string StudentId { get; set; }
    
        public virtual Graduate Graduate { get; set; }
        public virtual SoftSkill SoftSkill { get; set; }
        public virtual SoftSkillLevel SoftSkillLevel { get; set; }
    }
}
