//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VdQualification
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public int ExperienceId { get; set; }
        public int AbilityId { get; set; }
        public int CompetencyId { get; set; }
        public int CVId { get; set; }
    
        public virtual Ability Ability { get; set; }
        public virtual Competency Competency { get; set; }
        public virtual CV CV { get; set; }
        public virtual Experience Experience { get; set; }
    }
}
